#
# Full configuration through environment variables
#

default: &default
  adapter: <%=  ENV['DATABASE_ADAPTER'] || 'mysql2' %>
  timeout: <%=  ENV['DATABASE_TIMEOUT'] || 10000 %>
  url: <%=  ENV['DATABASE_URL'] %>
  port: <%=  ENV['DATABASE_PORT'] || 3306 %>
  encoding: utf8
  pool: <%=  ENV['DATABASE_POOL_SIZE'] || 20 %>

uat:
  <<: *default

production:
  <<: *default
